<!-- markdownlint-disable MD033 - Disabling as it has a better look for GitHub -->

- [ ] README.md (new application) updated
- [ ] package.json (new playbook) updated
- [ ] docs/ updated if needed

- Related Issue: #
- Closes: #
