#####################################################################
# Application Configuration - used for installing homelab apps
# This mainly uses docker so there are lot of configuration for that
#####################################################################
domain_name: example.duckdns.org

#####################################################################
# Mealie Configuration Secrets
#####################################################################
mealie_db_user: <db username>
mealie_db_password: <db pass>
oidc_mealie_config_url: <authentik / other oidc provider>
oidc_mealie_client_id: <client_id>
oidc_mealie_client_secret: <client_secret>
#####################################################################

#####################################################################
# pgadmin Configuration Secrets
#####################################################################
pgadmin_default_email: <default_email>
pgadmin_default_password: <pgadmin_password>
pgadmin_master_password: <pgadmin_master_password>
#####################################################################
