- name: Setup custom DNS - public
  become: true
  template:
    src: 02-local-dns.conf
    dest: "{{ docker_data_pihole }}/etc-dnsmasq.d/02-local-dns.conf"
    mode: "0777"

- name: Restart PiHole for DNS entries
  docker_container:
    name: pihole
    state: started
    restart: true