---
- name: Setup custom DNS - public
  template:
    src: 02-local-dns.conf
    dest: "{{ docker_data_pihole }}/etc-dnsmasq.d/02-local-dns.conf"
    mode: "0777"
  notify:
    - Restart PiHole for DNS entries

  handlers:
    - name: Restart PiHole for DNS entries
      docker_container:
        name: pihole
        state: started
        restart: true
