docker_application_folder: /home/{{ ansible_user }}/.docker

###########################################################################
# IT Tools Configuration
###########################################################################
it_tools_container_ip: 192.168.144.10
###########################################################################
# Stirling PDF Configuration
###########################################################################
docker_data_stirling_pdf: "{{ docker_application_folder }}/stirling-pdf"
stirling_pdf_container_ip: 192.168.144.11
###########################################################################
# Mealie Configuration
###########################################################################
docker_data_mealie: "{{ docker_application_folder }}/mealie"
mealie_container_ip: 192.168.101.10
mealie_db_container_ip: 192.168.101.11
mealie_db_name: mealie
mealie_url: mealie.{{ domain_name }}